### PR TITLE
Add 'always transparent' option.

### PR DESCRIPTION
**Pull request by alexanderad**
This PR adds "always transparent" option to the configuration, which allows you to make your top bar transparent always regardless windows state.

What would yuo say, @AMDG2?

### CODE REVIEW

**Comment by AMDG2** [comment]
Thank you for your contribution, but the point of this extension is not
to get the top bar always transparent. This make non sense, I am sorry.
You may develop your own extension, this should be pretty easy, or
easier than develop this one.

And let me suggest something, when you want to get involved in some free
software project you should start by asking the developers what to do.
Or, if you have an idea, let them know before start coding. That will
save you a lot of time ;)

**Comment by alexanderad** [comment]
Well, this is why I made it an option in extension settings and it is turned off by default. This PR appeared as an answer to that none of extensions in Gnome Shell store allow you to make the bar transparent in configurable way (like transparency level / style, etc).

**Comment by Sancho-Panza** [comment]
I think [Dynamic Panel Transparency](https://extensions.gnome.org/extension/1011/dynamic-panel-transparency/) is what you're looking for. Just set the minimum and the maximum opacity to 0%.

**Comment by alexanderad** [comment]
Thanks, @Sancho-Panza!

**Pull request closed without merging**
