### PR TITLE
added gnome 3.34 support

### PR DESCRIPTION
**Pull request by gesangtome**

### CODE REVIEW

**Comment by AMDG2** [comment]
Thanks for the PR, does it actually works, did you tested it?

**Comment by gesangtome** [comment]
@AMDG2 
Yes, I've tested it on my fedora 31, and it works fine.

**Comment by AMDG2** [comment]
OK, thanks! I'll merge then :)

**Comment by gesangtome** [comment]
@AMDG2 

> OK, thanks! I'll merge then :)

:+1  : )

**Pull request merged**
